### ISSUE TITLE
Missing NewYear plugin

### ISSUE THREAD

**Issue by paulchen** [RavuAlHemio/rocketbot#11]
One of the most important plugins of SharpIrcBot has not yet been ported to rocketbot: The [NewYearPlugin](https://github.com/RavuAlHemio/SharpIrcBot/blob/master/Plugins/NewYear/NewYearPlugin.cs)!

Without that plugin, no one will ever know when one year ends and the next one begins.

**Comment by RavuAlHemio** [comment]
damn, you're right
